steps:
  - script: yarn run build
    workingDirectory: "bs-log"
    displayName: "bs-log: yarn run build"

  - script: yarn run build
    workingDirectory: "bs-log-ppx"
    displayName: "bs-log-ppx: yarn run build"
