steps:
  - script: yarn run build
    workingDirectory: "re-log"
    displayName: "re-log: yarn run build"

  - script: yarn run build
    workingDirectory: "re-log-ppx"
    displayName: "re-log-ppx: yarn run build"
